- name: Write reminder in OSX bashrc
  blockinfile:
    path: "~{{ansible_user}}/.bashrc"
    marker: "# {mark}  agent.bash.disclaimer {{item|default('')}}"
    block: |
      ##
      # Not used for OSX.  See ~/.bash_profile
      ##
    create: yes
