- include_tasks: setup.yml
- name: Set bash-config file for Darwin
  set_fact:
    bash_config: "{{ansible_env.HOME}}/.bash_profile"
  when: ansible_os_family=="Darwin"

- name: Write reminder in OSX bashrc
  blockinfile:
    path: "{{ansible_env.HOME}}/.bashrc"
    marker: "# {mark}  agent.bash.disclaimer {{item|default('')}}"
    block: |
      ##
      # Not used for OSX.  See ~/.bash_profile
      ##
    create: yes
